project:
  type: website

website:
  title: "[Yeast Coast]{.headers}"
  navbar:
    right:
      - href: order.qmd
        text: "[Order]{.bodyfont}"
      - href: faq.qmd
        text: "[FAQ]{.bodyfont}"
      - href: recipes.qmd
        text: "[Recipes & Inspiration]{.bodyfont}"
  favicon: imgs/bread.png

execute:
  freeze: auto 
format:
  html:
    theme:
      - styles.scss
    toc: true



