project:
  type: website

website:
  title: "yeast-coast"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    scss: styles.scss
    toc: true



